server:
  port: 80

spring:
  application:
    name: minio-service

minio:
  enabled: true
  endpoint: http://192.168.133.110:9001
  username: minioadmin
  password: minioadmin
  bucket: my-bucket
  publicReadDir: public
